export const MARK_AS_FOUND = 'MARK_AS_FOUND';
export const SHOW_ANSWER_BOX = 'SHOW_ANSWER_BOX';
export const HIDE_ANSWER_BOX = 'HIDE_ANSWER_BOX';
export const SET_FEEDBACK = 'SET_FEEDBACK';
export const INCREMENT_NUM_OF_ATTEMPTS = 'INCREMENT_NUM_OF_ATTEMPTS';
export const RESET_STATE = 'RESET_STATE'
